// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSGbx7mXanoDLJtL-Mh7ZA5sT0C7p2xTI',
    appId: '1:224789237812:web:df8c1026e8d0508d6d7a61',
    messagingSenderId: '224789237812',
    projectId: 'myfyp-85c60',
    authDomain: 'myfyp-85c60.firebaseapp.com',
    storageBucket: 'myfyp-85c60.appspot.com',
    measurementId: 'G-CVPTCED01M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUUzYlE3kFkQXeTJ3GbsHkw1bdgu6YOSQ',
    appId: '1:224789237812:android:abd2732c9dad76226d7a61',
    messagingSenderId: '224789237812',
    projectId: 'myfyp-85c60',
    storageBucket: 'myfyp-85c60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYswvAEzopwASsqF-mbuUR5BNfM1S-OyA',
    appId: '1:224789237812:ios:661c3f04c1b9cc716d7a61',
    messagingSenderId: '224789237812',
    projectId: 'myfyp-85c60',
    storageBucket: 'myfyp-85c60.appspot.com',
    iosClientId: '224789237812-0j75em20k7qc937ue3opi9s2fmjqbnri.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );
}
